### ISSUE TITLE
calendar of online events

### ISSUE THREAD

**Issue by alainvd** [codeeu/codeweek#882]

**Comment by sp4c31nv4d3r** [comment]
Quick fix, which would not only help the filter for online-events: Style the date in the entries, so that they are way easier to read.

![date_display](https://user-images.githubusercontent.com/26871289/93076056-0dc12100-f687-11ea-8868-6f377442bfd4.PNG)
![date_display_2](https://user-images.githubusercontent.com/26871289/93076058-0e59b780-f687-11ea-94bb-126e62165f01.PNG)

**Comment by alainvd** [comment]
Emphasis on the date is done.

**Comment by sp4c31nv4d3r** [comment]
I can't find it - The list of activites under the map still look the same to me (chrome, firefox, android-chrome, cleared cache). What am I missing?

**Comment by alainvd** [comment]
The url is https://codeweek.eu/featured-activities for the calendar of featured activities :)

**Comment by sp4c31nv4d3r** [comment]
Ahhh! This is just a preview and will be added to not only the featured,
but all activity-cards?

alainvd <notifications@github.com> schrieb am Di., 22. Sep. 2020, 12:56:
